### ISSUE TITLE
Request JWT for new clients for identification

### ISSUE THREAD

**Issue by srad** [srad/eLogical#5]
Since we have an heterogeneous service based server infrastructure we can't use regular session cookies because of different domains (also not possible when clients are blocking cookoes, for security reasons).

We already have an open ticket for JWT to be implemented on the server. Once that is in place every new client must request a token and store it i.e. in the localStorage and every request to the server must provide this token.

Makes most sense to configure an axios instance as module or in main.js with is preconfigured to send the token with every request to the server (if a request is actually going to that server).

**Comment by Phate94** [comment]
Just merged the branch implementing this. Currently the app checks for a token once the app is loaded and requests a new token if needed. Before any other server-request this procedure is repeated.
